# Generated by Django 5.1 on 2024-09-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majors', models.CharField(max_length=255)),
                ('interest_arts', models.BooleanField(default=False)),
                ('interest_education', models.BooleanField(default=False)),
                ('interest_finance', models.BooleanField(default=False)),
                ('interest_healthcare', models.BooleanField(default=False)),
                ('interest_sustainability', models.BooleanField(default=False)),
                ('interest_social_impact', models.BooleanField(default=False)),
                ('interest_technology', models.BooleanField(default=False)),
                ('goal_learn', models.BooleanField(default=False)),
                ('goal_relations', models.BooleanField(default=False)),
                ('goal_idea', models.BooleanField(default=False)),
                ('goal_problems', models.BooleanField(default=False)),
                ('goal_win_support', models.BooleanField(default=False)),
                ('role_business', models.BooleanField(default=False)),
                ('role_engineer', models.BooleanField(default=False)),
                ('role_finance', models.BooleanField(default=False)),
                ('add_info', models.TextField(blank=True, null=True)),
                ('idea', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
