# Generated by Django 5.1 on 2024-09-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_algo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='Dhyey Mavani', max_length=255),
        ),
    ]
