# The name of the action
name: Django Tests
# When the action is triggered
on:
  push:
    branches:
      - master
      - main
      - '*/*'
      - '*'
  pull_request:
    branches:
      - master
      - main
      - '*/*'
      - '*'

# What to do when the action is triggered
jobs:
  # A job called 'build' - arbitrary
  build:
    # Run on a MACOS VM
    runs-on: macos-latest
    steps:
      # Checkout the GitHub repo
      - uses: actions/checkout@v2

      # Install Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Pip install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Move into the Django project folder (./app) and run pytest
      - name: Test with pytest
        working-directory: ./matching_backend
        run: pytest
